### ISSUE TITLE
Add a simple GUI to edit, save and view documents. 

### ISSUE THREAD

**Issue by AndreasTNT** [AndreasTNT/PyPress#1]
**Is your feature request related to a problem? Please describe.**
Currently, PyPress needs a GUI, editor widget and probably a menubar. 
**Describe the solution you'd like**
Code in these features.

- [ ] PyQt5 GUI for editing, viewing and for saving
- [ ]  Menubar
- [ ] Done

**Describe alternatives you've considered**
At least, I think these features are necessary for a word processor.

**Additional context**
Just a thought.

**Comment by linuxkettle** [comment]
Here's something I regretted when I did this: not using the system default open and save dialogs. Not sure how to do this in Tkinter, but it's not too hard in PyQt.

**Comment by AndreasTNT** [comment]
Closing issue, due to changed plans.
